### ISSUE TITLE
Contest log remains empty while live contest logging

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#2919]
### Discussed in https://github.com/magicbug/Cloudlog/discussions/2918

<div type='discussions-op-text'>

<sup>Originally posted by **dk5cr** January 14, 2024</sup>
Installed version is 2.6.1

I installed the current version and it shows a strange behaviour: 
Live contest logging with serial nr. and exchange schows me a worked stations as "worked before" in red, but the list at the bottom of the page remains empty. Is also is empty the whole time, no logged entries will be shown there. 
In the main list of QSO done the QSO are shown correctly with the attached parameters (serial/exchange). 

Is there a bug or did i missed some in the process of adding a new contest? 

Cheers and thanks 
Cornel, DK5CR 

PS: I didn't find a topic matching to this issue with the github search... If there is one please gimme a link to this. Thanks. 

**no entries on worked_before:**
![cloudlog_error_contest](https://github.com/magicbug/Cloudlog/assets/149412955/7d50e184-613a-4db6-a830-00a1460b7830)

**no entries at all:** 
![cloudlog_error_contest_no_entries](https://github.com/magicbug/Cloudlog/assets/149412955/fa0efed5-5827-49d6-bf1d-003b7ede1cac)

</div>

**Comment by magicbug** [comment]
Purely for debugging

Clean Login Session with no contest qsos prior

![Google Dev Tools](https://github.com/magicbug/Cloudlog/assets/84308/b740555c-bb48-4ece-a126-37d5b4ad56bf)

contesting.js?v2:506 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'qso')
    at refresh_qso_table (contesting.js?v2:506:23)
    at Object.success (contesting.js?v2:458:11)
    at u (jquery-3.3.1.min.js:2:27457)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2:28202)
    at k (jquery-3.3.1.min.js:2:77651)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2:79907)

**Comment by magicbug** [comment]
Now resolved in dev branch
